services:

  app:
    build: .
    ports:
      - '8080'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
